/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IResolver__factory } from "./IResolver__factory";
export { NameController__factory } from "./NameController__factory";
export { NamePriceOracle__factory } from "./NamePriceOracle__factory";
export { NameRegistry__factory } from "./NameRegistry__factory";
