/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IResolver } from "./IResolver";
export type { NameController } from "./NameController";
export type { NamePriceOracle } from "./NamePriceOracle";
export type { NameRegistry } from "./NameRegistry";
